log_level: debug

server:
  port: 8092
  contextPath: /offerApp

datasource:
  sampleapp:
    url: jdbc:h2:~/test
    username: SA
    password:
    driverClassName: org.h2.Driver
    defaultSchema:
    maxPoolSize: 10
    hibernate:
      hbm2ddl.method: create-drop
      show_sql: false
      format_sql: false
      dialect: org.hibernate.dialect.H2Dialect
